### ISSUE TITLE
Not downloading latest node versions

### ISSUE THREAD

**Issue by JasonScopServ** [dmrub/portable-node#2]
I'm trying to install node 6 or 7, but it fails to download the file. Says that it is not in gzip format.
`gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Result: 2
Error: Could not install node.js`

**Comment by dmrub** [comment]
Latest commit should fix this issue, please provide full version number (e.g. 6.9.5 not 6 and 7.5.0 not 7)  when specifying version at command line. The updated version will download  Node.js 6.9.5 by default.

**Comment by JasonScopServ** [comment]
Great thanks it work :)
