### ISSUE TITLE
How to install npm packages with portable node?

### ISSUE THREAD

**Issue by Zeedinstein** [dmrub/portable-node#3]
I'm trying to figure out how I can use the portable nodes instance of npm to install npm packages for my project? Is it possible to do this?

**Comment by dmrub** [comment]
Yes, you run in your project directory ```npm install <package-name>``` as usual.

**Comment by Zeedinstein** [comment]
Thanks, I ran ./bash-node* and then ran npm install from there. Because running npm in the directory was clashing with the globally installed npm.
